#!/usr/bin/env python
#
# -*- coding: utf-8 -*-
#
# Copyright © 2025 Genome Research Ltd. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# @author Marco M. Mosca <mm51@sanger.ac.uk>
#
# This file has been automatically generated by sqlacodegen to map
# the model of the tracking database together with its internal
# relationships.

import datetime
from typing import Optional

from sqlalchemy import (
    TIMESTAMP,
    Date,
    DateTime,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.mysql import BIGINT, CHAR, INTEGER, LONGBLOB, SMALLINT, TINYINT
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Designation(Base):
    __tablename__ = "designation"

    id_designation: Mapped[int] = mapped_column(INTEGER, primary_key=True)
    description: Mapped[str] = mapped_column(String(64), nullable=False)

    instrument_designation: Mapped[list["InstrumentDesignation"]] = relationship(
        "InstrumentDesignation", back_populates="designation"
    )


class EntityType(Base):
    __tablename__ = "entity_type"
    __table_args__ = (Index("iscurrent", "iscurrent"),)

    id_entity_type: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    description: Mapped[str] = mapped_column(
        CHAR(64), nullable=False, server_default=text("''")
    )
    iscurrent: Mapped[int] = mapped_column(
        TINYINT, nullable=False, server_default=text("'0'")
    )

    event_type: Mapped[list["EventType"]] = relationship(
        "EventType", back_populates="entity_type"
    )
    tag_frequency: Mapped[list["TagFrequency"]] = relationship(
        "TagFrequency", back_populates="entity_type"
    )


class InstrumentModDict(Base):
    __tablename__ = "instrument_mod_dict"

    id_instrument_mod_dict: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    description: Mapped[str] = mapped_column(
        CHAR(128), nullable=False, server_default=text("''")
    )
    revision: Mapped[Optional[str]] = mapped_column(CHAR(64))

    instrument_mod: Mapped[list["InstrumentMod"]] = relationship(
        "InstrumentMod", back_populates="instrument_mod_dict"
    )


class InstrumentStatusDict(Base):
    __tablename__ = "instrument_status_dict"
    __table_args__ = (
        Index("unique_instrdict_description", "description", unique=True),
    )

    id_instrument_status_dict: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    description: Mapped[str] = mapped_column(
        CHAR(64), nullable=False, server_default=text("''")
    )
    iscurrent: Mapped[int] = mapped_column(
        TINYINT, nullable=False, server_default=text("'1'")
    )

    instrument_status: Mapped[list["InstrumentStatus"]] = relationship(
        "InstrumentStatus", back_populates="instrument_status_dict"
    )


class Manufacturer(Base):
    __tablename__ = "manufacturer"
    __table_args__ = (Index("name", "name", unique=True),)

    id_manufacturer: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    name: Mapped[Optional[str]] = mapped_column(CHAR(128))

    instrument_format: Mapped[list["InstrumentFormat"]] = relationship(
        "InstrumentFormat", back_populates="manufacturer"
    )


class RunLaneStatusDict(Base):
    __tablename__ = "run_lane_status_dict"
    __table_args__ = (Index("unique_rlstdict_description", "description", unique=True),)

    id_run_lane_status_dict: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    description: Mapped[str] = mapped_column(
        String(64), primary_key=True, server_default=text("''")
    )

    run_lane_status: Mapped[list["RunLaneStatus"]] = relationship(
        "RunLaneStatus", back_populates="run_lane_status_dict"
    )


class RunStatusDict(Base):
    __tablename__ = "run_status_dict"
    __table_args__ = (
        Index("unique_rstdict_description", "description", unique=True),
        Index("unique_rstdict_temporali", "temporal_index", unique=True),
    )

    id_run_status_dict: Mapped[int] = mapped_column(Integer, primary_key=True)
    description: Mapped[str] = mapped_column(
        String(64), nullable=False, server_default=text("''")
    )
    iscurrent: Mapped[int] = mapped_column(
        TINYINT, nullable=False, server_default=text("'1'")
    )
    temporal_index: Mapped[int] = mapped_column(SMALLINT, nullable=False)

    run_status: Mapped[list["RunStatus"]] = relationship(
        "RunStatus", back_populates="run_status_dict"
    )


class Tag(Base):
    __tablename__ = "tag"
    __table_args__ = (Index("u_tag", "tag", unique=True),)

    id_tag: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    tag: Mapped[str] = mapped_column(
        CHAR(32), nullable=False, server_default=text("''")
    )
    incompatible_tag: Mapped[Optional[str]] = mapped_column(CHAR(32))

    tag_frequency: Mapped[list["TagFrequency"]] = relationship(
        "TagFrequency", back_populates="tag"
    )
    tag_run: Mapped[list["TagRun"]] = relationship("TagRun", back_populates="tag")
    tag_run_lane: Mapped[list["TagRunLane"]] = relationship(
        "TagRunLane", back_populates="tag"
    )


class User(Base):
    __tablename__ = "user"
    __table_args__ = (
        Index("rf_id", "rfid", unique=True),
        Index("uidx_username", "username", unique=True),
    )

    id_user: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    iscurrent: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'1'")
    )
    username: Mapped[Optional[str]] = mapped_column(CHAR(128))
    rfid: Mapped[Optional[str]] = mapped_column(String(64))

    annotation: Mapped[list["Annotation"]] = relationship(
        "Annotation", back_populates="user"
    )
    user2usergroup: Mapped[list["User2usergroup"]] = relationship(
        "User2usergroup", back_populates="user"
    )
    event: Mapped[list["Event"]] = relationship("Event", back_populates="user")
    instrument_mod: Mapped[list["InstrumentMod"]] = relationship(
        "InstrumentMod", back_populates="user"
    )
    instrument_status: Mapped[list["InstrumentStatus"]] = relationship(
        "InstrumentStatus", back_populates="user"
    )
    run_status: Mapped[list["RunStatus"]] = relationship(
        "RunStatus", back_populates="user"
    )
    tag_run: Mapped[list["TagRun"]] = relationship("TagRun", back_populates="user")
    run_lane_status: Mapped[list["RunLaneStatus"]] = relationship(
        "RunLaneStatus", back_populates="user"
    )
    tag_run_lane: Mapped[list["TagRunLane"]] = relationship(
        "TagRunLane", back_populates="user"
    )


class Usergroup(Base):
    __tablename__ = "usergroup"

    groupname: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default=text("''")
    )
    id_usergroup: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    is_public: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'0'")
    )
    iscurrent: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'1'")
    )
    description: Mapped[Optional[str]] = mapped_column(
        String(128), server_default=text("''")
    )

    user2usergroup: Mapped[list["User2usergroup"]] = relationship(
        "User2usergroup", back_populates="usergroup"
    )


class Annotation(Base):
    __tablename__ = "annotation"
    __table_args__ = (
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="ann_idu"),
        Index("ann_idu", "id_user"),
    )

    id_annotation: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    date: Mapped[datetime.datetime] = mapped_column(
        DateTime, nullable=False, server_default=text("'0000-00-00 00:00:00'")
    )
    comment: Mapped[str] = mapped_column(Text, nullable=False)
    attachment_name: Mapped[Optional[str]] = mapped_column(String(128))
    attachment: Mapped[Optional[bytes]] = mapped_column(LONGBLOB)

    user: Mapped["User"] = relationship("User", back_populates="annotation")
    instrument_annotation: Mapped[list["InstrumentAnnotation"]] = relationship(
        "InstrumentAnnotation", back_populates="annotation"
    )
    instrument_status_annotation: Mapped[list["InstrumentStatusAnnotation"]] = (
        relationship("InstrumentStatusAnnotation", back_populates="annotation")
    )
    run_annotation: Mapped[list["RunAnnotation"]] = relationship(
        "RunAnnotation", back_populates="annotation"
    )
    run_lane_annotation: Mapped[list["RunLaneAnnotation"]] = relationship(
        "RunLaneAnnotation", back_populates="annotation"
    )


class EventType(Base):
    __tablename__ = "event_type"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_entity_type"], ["entity_type.id_entity_type"], name="evt_entityt"
        ),
        Index("evt_entityt", "id_entity_type"),
    )

    id_event_type: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    description: Mapped[str] = mapped_column(
        CHAR(64), nullable=False, server_default=text("''")
    )
    id_entity_type: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )

    entity_type: Mapped["EntityType"] = relationship(
        "EntityType", back_populates="event_type"
    )
    event: Mapped[list["Event"]] = relationship("Event", back_populates="event_type")


class InstrumentFormat(Base):
    __tablename__ = "instrument_format"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_manufacturer"], ["manufacturer.id_manufacturer"], name="id_mfctr"
        ),
        Index("id_mfctr", "id_manufacturer"),
    )

    id_instrument_format: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_manufacturer: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    iscurrent: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'0'")
    )
    default_tiles: Mapped[int] = mapped_column(
        INTEGER, nullable=False, server_default=text("'0'")
    )
    default_columns: Mapped[int] = mapped_column(
        INTEGER, nullable=False, server_default=text("'0'")
    )
    model: Mapped[Optional[str]] = mapped_column(CHAR(64))
    days_between_washes: Mapped[Optional[int]] = mapped_column(INTEGER)
    runs_between_washes: Mapped[Optional[int]] = mapped_column(INTEGER)

    manufacturer: Mapped["Manufacturer"] = relationship(
        "Manufacturer", back_populates="instrument_format"
    )
    instrument: Mapped[list["Instrument"]] = relationship(
        "Instrument", back_populates="instrument_format"
    )
    run: Mapped[list["Run"]] = relationship("Run", back_populates="instrument_format")


class TagFrequency(Base):
    __tablename__ = "tag_frequency"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_entity_type"], ["entity_type.id_entity_type"], name="tf_id_entity_type"
        ),
        ForeignKeyConstraint(["id_tag"], ["tag.id_tag"], name="tf_id_tag"),
        Index("tf_id_entity_type", "id_entity_type"),
        Index("tf_id_tag", "id_tag"),
    )

    id_tag_frequency: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_tag: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_entity_type: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    frequency: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'1'")
    )

    entity_type: Mapped["EntityType"] = relationship(
        "EntityType", back_populates="tag_frequency"
    )
    tag: Mapped["Tag"] = relationship("Tag", back_populates="tag_frequency")


class User2usergroup(Base):
    __tablename__ = "user2usergroup"
    __table_args__ = (
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="id_user"),
        ForeignKeyConstraint(
            ["id_usergroup"], ["usergroup.id_usergroup"], name="id_usergroup"
        ),
        Index("id_user", "id_user"),
        Index("id_usergroup", "id_usergroup"),
    )

    id_user_usergroup: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    id_usergroup: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    level: Mapped[Optional[int]] = mapped_column(TINYINT)

    user: Mapped["User"] = relationship("User", back_populates="user2usergroup")
    usergroup: Mapped["Usergroup"] = relationship(
        "Usergroup", back_populates="user2usergroup"
    )


class Event(Base):
    __tablename__ = "event"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_event_type"], ["event_type.id_event_type"], name="event_ibfk_1"
        ),
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="ev_u"),
        Index("ev_u", "id_user"),
        Index("id_event_type", "id_event_type"),
    )

    id_event: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_event_type: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    date: Mapped[datetime.datetime] = mapped_column(
        DateTime, nullable=False, server_default=text("'0000-00-00 00:00:00'")
    )
    entity_id: Mapped[int] = mapped_column(
        BIGINT,
        nullable=False,
        server_default=text("'0'"),
        comment="the id of the entity having id_event_type.id_entity_type",
    )
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    notification_sent: Mapped[datetime.datetime] = mapped_column(
        TIMESTAMP, nullable=False, server_default=text("'0000-00-00 00:00:00'")
    )
    description: Mapped[Optional[str]] = mapped_column(String(1024))

    event_type: Mapped["EventType"] = relationship("EventType", back_populates="event")
    user: Mapped["User"] = relationship("User", back_populates="event")


class Instrument(Base):
    __tablename__ = "instrument"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_instrument_format"],
            ["instrument_format.id_instrument_format"],
            name="id_if",
        ),
        Index("id_if", "id_instrument_format"),
        Index("name", "name", unique=True),
    )

    id_instrument: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    name: Mapped[str] = mapped_column(
        CHAR(32), primary_key=True, server_default=text("''")
    )
    id_instrument_format: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    external_name: Mapped[str] = mapped_column(
        CHAR(32), nullable=False, server_default=text("''")
    )
    serial: Mapped[str] = mapped_column(
        CHAR(128), nullable=False, server_default=text("''")
    )
    iscurrent: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'0'")
    )
    ipaddr: Mapped[Optional[str]] = mapped_column(CHAR(15), server_default=text("''"))
    instrument_comp: Mapped[Optional[str]] = mapped_column(String(32))
    mirroring_host: Mapped[Optional[str]] = mapped_column(String(16))
    staging_dir: Mapped[Optional[str]] = mapped_column(String(128))
    latest_contact: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    percent_complete: Mapped[Optional[int]] = mapped_column(TINYINT)
    lab: Mapped[Optional[str]] = mapped_column(String(10))

    instrument_format: Mapped["InstrumentFormat"] = relationship(
        "InstrumentFormat", back_populates="instrument"
    )
    instrument_annotation: Mapped[list["InstrumentAnnotation"]] = relationship(
        "InstrumentAnnotation", back_populates="instrument"
    )
    instrument_designation: Mapped[list["InstrumentDesignation"]] = relationship(
        "InstrumentDesignation", back_populates="instrument"
    )
    instrument_mod: Mapped[list["InstrumentMod"]] = relationship(
        "InstrumentMod", back_populates="instrument"
    )
    instrument_status: Mapped[list["InstrumentStatus"]] = relationship(
        "InstrumentStatus", back_populates="instrument"
    )
    run: Mapped[list["Run"]] = relationship("Run", back_populates="instrument")


class InstrumentAnnotation(Base):
    __tablename__ = "instrument_annotation"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_annotation"], ["annotation.id_annotation"], name="ia_ida"
        ),
        ForeignKeyConstraint(
            ["id_instrument"], ["instrument.id_instrument"], name="ia_idinstrument"
        ),
        Index("ia_ida", "id_annotation"),
        Index("ia_idinstrument", "id_instrument"),
    )

    id_instrument_annotation: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_instrument: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_annotation: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )

    annotation: Mapped["Annotation"] = relationship(
        "Annotation", back_populates="instrument_annotation"
    )
    instrument: Mapped["Instrument"] = relationship(
        "Instrument", back_populates="instrument_annotation"
    )


class InstrumentDesignation(Base):
    __tablename__ = "instrument_designation"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_designation"], ["designation.id_designation"], name="id_id"
        ),
        ForeignKeyConstraint(
            ["id_instrument"], ["instrument.id_instrument"], name="id_ii"
        ),
        Index("id_id", "id_designation"),
        Index("id_ii", "id_instrument"),
    )

    id_instrument_designation: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_instrument: Mapped[int] = mapped_column(BIGINT, nullable=False)
    id_designation: Mapped[int] = mapped_column(INTEGER, nullable=False)

    designation: Mapped["Designation"] = relationship(
        "Designation", back_populates="instrument_designation"
    )
    instrument: Mapped["Instrument"] = relationship(
        "Instrument", back_populates="instrument_designation"
    )


class InstrumentMod(Base):
    __tablename__ = "instrument_mod"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_instrument"], ["instrument.id_instrument"], name="im_id_i"
        ),
        ForeignKeyConstraint(
            ["id_instrument_mod_dict"],
            ["instrument_mod_dict.id_instrument_mod_dict"],
            name="im_id_imd",
        ),
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="im_id_user"),
        Index("im_id_i", "id_instrument"),
        Index("im_id_imd", "id_instrument_mod_dict"),
        Index("im_id_user", "id_user"),
    )

    id_instrument_mod: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_instrument: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_instrument_mod_dict: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    date_added: Mapped[datetime.datetime] = mapped_column(DateTime, nullable=False)
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    iscurrent: Mapped[int] = mapped_column(
        TINYINT, nullable=False, server_default=text("'0'")
    )
    date_removed: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)

    instrument: Mapped["Instrument"] = relationship(
        "Instrument", back_populates="instrument_mod"
    )
    instrument_mod_dict: Mapped["InstrumentModDict"] = relationship(
        "InstrumentModDict", back_populates="instrument_mod"
    )
    user: Mapped["User"] = relationship("User", back_populates="instrument_mod")


class InstrumentStatus(Base):
    __tablename__ = "instrument_status"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_instrument"], ["instrument.id_instrument"], name="is_idi"
        ),
        ForeignKeyConstraint(
            ["id_instrument_status_dict"],
            ["instrument_status_dict.id_instrument_status_dict"],
            name="is_idisd",
        ),
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="is_idu"),
        Index("i_iscurrent", "iscurrent"),
        Index("is_idi", "id_instrument"),
        Index("is_idisd", "id_instrument_status_dict"),
        Index("is_idu", "id_user"),
    )

    id_instrument_status: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_instrument: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_instrument_status_dict: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    date: Mapped[datetime.datetime] = mapped_column(
        DateTime, nullable=False, server_default=text("'0000-00-00 00:00:00'")
    )
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    iscurrent: Mapped[int] = mapped_column(
        TINYINT, nullable=False, server_default=text("'0'")
    )
    comment: Mapped[Optional[str]] = mapped_column(Text)

    instrument: Mapped["Instrument"] = relationship(
        "Instrument", back_populates="instrument_status"
    )
    instrument_status_dict: Mapped["InstrumentStatusDict"] = relationship(
        "InstrumentStatusDict", back_populates="instrument_status"
    )
    user: Mapped["User"] = relationship("User", back_populates="instrument_status")
    instrument_status_annotation: Mapped[list["InstrumentStatusAnnotation"]] = (
        relationship("InstrumentStatusAnnotation", back_populates="instrument_status")
    )


class Run(Base):
    __tablename__ = "run"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_instrument"], ["instrument.id_instrument"], name="id_instrument"
        ),
        ForeignKeyConstraint(
            ["id_instrument_format"],
            ["instrument_format.id_instrument_format"],
            name="r_idif",
        ),
        Index("id_instrument", "id_instrument"),
        Index("r_id_run_pair", "id_run_pair"),
        Index("r_idif", "id_instrument_format"),
    )

    id_run: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_instrument: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    priority: Mapped[int] = mapped_column(
        TINYINT, nullable=False, server_default=text("'0'")
    )
    is_paired: Mapped[int] = mapped_column(
        TINYINT, nullable=False, server_default=text("'0'")
    )
    id_instrument_format: Mapped[int] = mapped_column(BIGINT, nullable=False)
    team: Mapped[str] = mapped_column(CHAR(10), nullable=False)
    actual_cycle_count: Mapped[Optional[int]] = mapped_column(BIGINT)
    expected_cycle_count: Mapped[Optional[int]] = mapped_column(BIGINT)
    id_run_pair: Mapped[Optional[int]] = mapped_column(BIGINT)
    batch_id: Mapped[Optional[int]] = mapped_column(BIGINT)
    flowcell_id: Mapped[Optional[str]] = mapped_column(String(64))
    folder_name: Mapped[Optional[str]] = mapped_column(String(64))
    folder_path_glob: Mapped[Optional[str]] = mapped_column(String(256))

    instrument: Mapped["Instrument"] = relationship("Instrument", back_populates="run")
    instrument_format: Mapped["InstrumentFormat"] = relationship(
        "InstrumentFormat", back_populates="run"
    )
    run_annotation: Mapped[list["RunAnnotation"]] = relationship(
        "RunAnnotation", back_populates="run"
    )
    run_lane: Mapped[list["RunLane"]] = relationship("RunLane", back_populates="run")
    run_read: Mapped[list["RunRead"]] = relationship("RunRead", back_populates="run")
    run_status: Mapped[list["RunStatus"]] = relationship(
        "RunStatus", back_populates="run"
    )
    st_cache: Mapped[list["StCache"]] = relationship("StCache", back_populates="run")
    tag_run: Mapped[list["TagRun"]] = relationship("TagRun", back_populates="run")


class InstrumentStatusAnnotation(Base):
    __tablename__ = "instrument_status_annotation"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_annotation"], ["annotation.id_annotation"], name="isa_ida"
        ),
        ForeignKeyConstraint(
            ["id_instrument_status"],
            ["instrument_status.id_instrument_status"],
            name="isa_idis",
        ),
        Index(
            "id_instrument_status", "id_instrument_status", "id_annotation", unique=True
        ),
        Index("isa_ida", "id_annotation"),
    )

    id_instrument_status_annotation: Mapped[int] = mapped_column(
        BIGINT, primary_key=True
    )
    id_instrument_status: Mapped[int] = mapped_column(BIGINT, nullable=False)
    id_annotation: Mapped[int] = mapped_column(BIGINT, nullable=False)

    annotation: Mapped["Annotation"] = relationship(
        "Annotation", back_populates="instrument_status_annotation"
    )
    instrument_status: Mapped["InstrumentStatus"] = relationship(
        "InstrumentStatus", back_populates="instrument_status_annotation"
    )


class RunAnnotation(Base):
    __tablename__ = "run_annotation"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_annotation"], ["annotation.id_annotation"], name="ra_ida"
        ),
        ForeignKeyConstraint(["id_run"], ["run.id_run"], name="ra_idrun"),
        Index("ra_ida", "id_annotation"),
        Index("ra_idrun", "id_run"),
    )

    id_run_annotation: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_annotation: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    run_current_ok: Mapped[Optional[int]] = mapped_column(TINYINT)
    current_cycle: Mapped[Optional[int]] = mapped_column(BIGINT)

    annotation: Mapped["Annotation"] = relationship(
        "Annotation", back_populates="run_annotation"
    )
    run: Mapped["Run"] = relationship("Run", back_populates="run_annotation")


class RunLane(Base):
    __tablename__ = "run_lane"
    __table_args__ = (
        ForeignKeyConstraint(["id_run"], ["run.id_run"], name="id_rn"),
        Index("id_rn", "id_run"),
        Index("uq_id_run_position", "id_run", "position", unique=True),
    )

    id_run_lane: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    tile_count: Mapped[int] = mapped_column(
        INTEGER, nullable=False, server_default=text("'0'")
    )
    tracks: Mapped[int] = mapped_column(
        INTEGER, nullable=False, server_default=text("'0'"), comment="Double=2"
    )
    position: Mapped[Optional[int]] = mapped_column(INTEGER, server_default=text("'0'"))

    run: Mapped["Run"] = relationship("Run", back_populates="run_lane")
    run_lane_annotation: Mapped[list["RunLaneAnnotation"]] = relationship(
        "RunLaneAnnotation", back_populates="run_lane"
    )
    run_lane_status: Mapped[list["RunLaneStatus"]] = relationship(
        "RunLaneStatus", back_populates="run_lane"
    )
    tag_run_lane: Mapped[list["TagRunLane"]] = relationship(
        "TagRunLane", back_populates="run_lane"
    )


class RunRead(Base):
    __tablename__ = "run_read"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_run"],
            ["run.id_run"],
            ondelete="RESTRICT",
            onupdate="RESTRICT",
            name="fk_read_id_run",
        ),
        Index("fk_read_id_run", "id_run"),
        Index("uq_id_run_order", "id_run", "read_order", unique=True),
    )

    id_run_read: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    intervention: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'0'")
    )
    read_order: Mapped[Optional[int]] = mapped_column(
        INTEGER, server_default=text("'0'")
    )
    expected_cycle_count: Mapped[Optional[int]] = mapped_column(BIGINT)

    run: Mapped["Run"] = relationship("Run", back_populates="run_read")


class RunStatus(Base):
    __tablename__ = "run_status"
    __table_args__ = (
        ForeignKeyConstraint(["id_run"], ["run.id_run"], name="id_run"),
        ForeignKeyConstraint(
            ["id_run_status_dict"],
            ["run_status_dict.id_run_status_dict"],
            name="id_rsd",
        ),
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="id_usr2"),
        Index("id_rsd", "id_run_status_dict"),
        Index("id_usr2", "id_user"),
        Index("rs_iscurrent", "iscurrent"),
        Index("run_date_state", "id_run", "date", "id_run_status_dict"),
    )

    id_run_status: Mapped[int] = mapped_column(Integer, primary_key=True)
    id_run: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    date: Mapped[datetime.datetime] = mapped_column(
        DateTime, nullable=False, server_default=text("'0000-00-00 00:00:00'")
    )
    id_run_status_dict: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("'0'")
    )
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    iscurrent: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'0'")
    )

    run: Mapped["Run"] = relationship("Run", back_populates="run_status")
    run_status_dict: Mapped["RunStatusDict"] = relationship(
        "RunStatusDict", back_populates="run_status"
    )
    user: Mapped["User"] = relationship("User", back_populates="run_status")


class StCache(Base):
    __tablename__ = "st_cache"
    __table_args__ = (
        ForeignKeyConstraint(["id_run"], ["run.id_run"], name="stc_id_run"),
        Index("stc_id_run", "id_run"),
        Index("type", "type"),
    )

    id_cache: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    type: Mapped[str] = mapped_column(
        CHAR(64), nullable=False, server_default=text("''")
    )
    content: Mapped[str] = mapped_column(
        CHAR(255), nullable=False, server_default=text("''")
    )

    run: Mapped["Run"] = relationship("Run", back_populates="st_cache")


class TagRun(Base):
    __tablename__ = "tag_run"
    __table_args__ = (
        ForeignKeyConstraint(["id_run"], ["run.id_run"], name="tr_id_run"),
        ForeignKeyConstraint(["id_tag"], ["tag.id_tag"], name="tr_id_tag"),
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="tr_id_user"),
        Index("tr_id_run", "id_run"),
        Index("tr_id_tag", "id_tag"),
        Index("tr_id_user", "id_user"),
        Index("u_idrun_idtag", "id_run", "id_tag", unique=True),
    )

    id_tag_run: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_tag: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    date: Mapped[datetime.date] = mapped_column(
        Date, nullable=False, server_default=text("'0000-00-00'")
    )

    run: Mapped["Run"] = relationship("Run", back_populates="tag_run")
    tag: Mapped["Tag"] = relationship("Tag", back_populates="tag_run")
    user: Mapped["User"] = relationship("User", back_populates="tag_run")


class RunLaneAnnotation(Base):
    __tablename__ = "run_lane_annotation"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_annotation"], ["annotation.id_annotation"], name="rla_ida"
        ),
        ForeignKeyConstraint(
            ["id_run_lane"], ["run_lane.id_run_lane"], name="rla_idrunlane"
        ),
        Index("rla_ida", "id_annotation"),
        Index("rla_idrunlane", "id_run_lane"),
    )

    id_run_lane_annotation: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run_lane: Mapped[int] = mapped_column(BIGINT, nullable=False)
    id_annotation: Mapped[int] = mapped_column(BIGINT, nullable=False)

    annotation: Mapped["Annotation"] = relationship(
        "Annotation", back_populates="run_lane_annotation"
    )
    run_lane: Mapped["RunLane"] = relationship(
        "RunLane", back_populates="run_lane_annotation"
    )


class RunLaneStatus(Base):
    __tablename__ = "run_lane_status"
    __table_args__ = (
        ForeignKeyConstraint(["id_run_lane"], ["run_lane.id_run_lane"], name="rls_rl"),
        ForeignKeyConstraint(
            ["id_run_lane_status_dict"],
            ["run_lane_status_dict.id_run_lane_status_dict"],
            name="rls_rlsd",
        ),
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="rls_user"),
        Index("rls_rl", "id_run_lane"),
        Index("rls_rlsd", "id_run_lane_status_dict"),
        Index("rls_user", "id_user"),
    )

    id_run_lane_status: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run_lane: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    date: Mapped[datetime.datetime] = mapped_column(
        DateTime, nullable=False, server_default=text("'0000-00-00 00:00:00'")
    )
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    iscurrent: Mapped[int] = mapped_column(
        TINYINT(1), nullable=False, server_default=text("'0'")
    )
    id_run_lane_status_dict: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )

    run_lane: Mapped["RunLane"] = relationship(
        "RunLane", back_populates="run_lane_status"
    )
    run_lane_status_dict: Mapped["RunLaneStatusDict"] = relationship(
        "RunLaneStatusDict", back_populates="run_lane_status"
    )
    user: Mapped["User"] = relationship("User", back_populates="run_lane_status")


class TagRunLane(Base):
    __tablename__ = "tag_run_lane"
    __table_args__ = (
        ForeignKeyConstraint(
            ["id_run_lane"], ["run_lane.id_run_lane"], name="trl_id_run_lane"
        ),
        ForeignKeyConstraint(["id_tag"], ["tag.id_tag"], name="trl_id_tag"),
        ForeignKeyConstraint(["id_user"], ["user.id_user"], name="trl_id_user"),
        Index("trl_id_run_lane", "id_run_lane"),
        Index("trl_id_tag", "id_tag"),
        Index("trl_id_user", "id_user"),
    )

    id_tag_run_lane: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    id_run_lane: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_tag: Mapped[int] = mapped_column(
        BIGINT, nullable=False, server_default=text("'0'")
    )
    id_user: Mapped[int] = mapped_column(BIGINT, nullable=False)
    date: Mapped[datetime.date] = mapped_column(
        Date, nullable=False, server_default=text("'0000-00-00'")
    )

    run_lane: Mapped["RunLane"] = relationship("RunLane", back_populates="tag_run_lane")
    tag: Mapped["Tag"] = relationship("Tag", back_populates="tag_run_lane")
    user: Mapped["User"] = relationship("User", back_populates="tag_run_lane")
